CREATE TABLE IF NOT EXISTS system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    role TEXT NOT NULL,
    message TEXT NOT NULL,
    level TEXT DEFAULT 'INFO'
);

-- Index for faster queries
CREATE INDEX IF NOT EXISTS system_logs_created_at_idx ON system_logs (created_at DESC);
